codecov:
  bot: "codecov-io"
coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 2%
        paths:
          - "timeeval"
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false
    patch:
      default:
        informational: true
comment:
  require_changes: true
  require_base: true
  require_head: true
ignore:
  - "tests/*"
  - "timeeval_experiments/*"
  - "timeeval/algorithms/*"
